on:
  push:
    branches:
    - main
    - release/*

jobs:
    visualize:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "diagram.svg"
          should_push: false
      - uses: actions/upload-artifact@v4.6.2
        with:
            path: "diagram.svg"
